fix(xo-web): empty list of options in selects (#8363)
Introduced by a386680d90bee4fe9987aebc8fb8001a08f240d2
Fixes #8361
See https://github.com/bvaughn/react-virtualized/issues/1871

react-virtualized@9.22.6 seems to be breaking old versions of React
Error in browser console: `TypeError: p.createRef is not a function`